fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"

# profile module layout, default include ntp module
    ntp: "https://github.com/puppetlabs/puppetlabs-ntp.git"
    apt: "https://github.com/puppetlabs/puppetlabs-apt.git"
    rspec_monitor: "git://github.com/pgomersbach/test-rspec_monitor.git"
    terraform: "https://github.com/inkblot/puppet-terraform.git"
    staging: "https://github.com/nanliu/puppet-staging.git"
    vcsrepo: "https://github.com/puppetlabs/puppetlabs-vcsrepo"
    ca_cert: "https://github.com/pcfens/puppet-ca_cert.git"

  symlinks:
    profile_development: "#{source_dir}"
