fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    ntp: "https://github.com/puppetlabs/puppetlabs-ntp.git"
    apt: "https://github.com/puppetlabs/puppetlabs-apt.git"
    rspec_monitor: "git://github.com/pgomersbach/test-rspec_monitor.git"
    hashicorp: "https://github.com/inkblot/puppet-hashicorp.git"
    gnupg: "https://github.com/dgolja/golja-gnupg.git"
    staging: "https://github.com/nanliu/puppet-staging.git"
    vcsrepo: "https://github.com/puppetlabs/puppetlabs-vcsrepo"
    ca_cert: "https://github.com/pcfens/puppet-ca_cert.git"
    archive: "https://github.com/voxpupuli/puppet-archive.git"
    ansible: "https://github.com/icann-dns/puppet-ansible.git"
    tea: "https://github.com/icann-dns/puppet-tea"

  symlinks:
    profile_development: "#{source_dir}"
